### PR TITLE
Aws eks stakater

### PR DESCRIPTION
**Pull request by aliartiza75**

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins-delivery.workshop.stakater.com/job/nordmart-apps/job/nordmart-dev-tools/job/PR-10/1/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Tests have been passed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins-delivery.workshop.stakater.com/job/nordmart/job/nordmart-dev-tools/job/PR-10/2/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Tests have been passed!

**Review by ahmedwaleedmalik — APPROVED** [review]

**Review by stakater-user — APPROVED** [review]

**Pull request merged**
